services:
  naive:
    image: caddy-forwardproxy-naive:v2.10.0
    container_name: proxy-caddy-naive
    restart: always
    network_mode: host
    tty: true
    volumes:
      - ./Caddyfile:/etc/naiveproxy/Caddyfile:ro
      - ./data:/root/.local/share/caddy
      - ${WEB_SOURCE:-./www}:/var/www:ro
      - ./log:/var/log/caddy
